/**
 * sample_data.js — Datos iniciales de demostración con Business Services por Mercado y Fechas para SLA
 */
const initialChangesData = [
  {
    id: 'CHG-DEMO-001',
    spId: 1001,
    numeroChange: 'CHG0089201',
    ritm: 'RITM0145220',
    solicitante: 'Andrés Delgado',
    pais: 'Brasil',
    businessService: 'E-Commerce & Sales Brasil',
    producto: 'Nescafé',
    descripcion: 'Optimización del proceso de checkout B2B con cálculo automático de impuestos regionales',
    engenheiro: 'Carlos Mendoza',
    horasEstimadas: 18,
    horasAprovadas: 18,
    tipoChange: 'Mejora',
    faseAtual: 'Execucao',
    statusAprovacao: 'Aprovado',
    aprovadorNome: 'Mariana Silva',
    aprovadorEmail: 'mariana.silva@nestle.com',
    analise: 'Ajuste en el módulo de cálculo de impuestos para regiones brasileñas.',
    rollback: 'Reactivar versión anterior del módulo de checkout v2.3.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico & Requerimientos', accion: 'Revisión de reglas de negocio fiscales', horas: 4, fechaTentativa: '2026-08-05' },
      { fase: '3. Desarrollo Backend / APIs', accion: 'Implementación del módulo de cálculo', horas: 10, fechaTentativa: '2026-08-10' },
      { fase: '6. Pruebas QA & Regresión', accion: 'Pruebas con escenarios fiscales reales', horas: 4, fechaTentativa: '2026-08-12' }
    ],
    d1: '2026-08-01', d2: '2026-08-03', d3: '2026-08-05', d4: '2026-08-07',
    d5: '2026-08-09', d6: '2026-08-10', d7: '2026-08-14', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-01', usuario: 'Andrés Delgado' },
      { de: 'Abertura', a: 'Execucao', fecha: '2026-08-14', usuario: 'Carlos Mendoza' }
    ],
    fechaCreacion: '2026-08-01',
    fechaCierre: '',
    ultimaModificacao: '2026-08-14T10:00:00Z',
    modificadoPor: 'Carlos Mendoza'
  },
  {
    id: 'CHG-DEMO-002',
    spId: 1002,
    numeroChange: 'CHG0089245',
    ritm: 'RITM0145300',
    solicitante: 'Camila Restrepo',
    pais: 'Mexico',
    businessService: 'Customer Experience México',
    producto: 'Purina Pro Plan',
    descripcion: 'Alertas automáticas de stock bajo para prevenir quiebres en canal moderno',
    engenheiro: 'Lucía Fernández',
    horasEstimadas: 22,
    horasAprovadas: 22,
    tipoChange: 'Mejora',
    faseAtual: 'Analise',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Roberto Gómez',
    aprovadorEmail: 'roberto.gomez@nestle.com',
    analise: 'Configurar triggers en el ERP para stock mínimo por SKU y canal.',
    rollback: 'Desactivar triggers configurados en el ERP.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico & Requerimientos', accion: 'Mapeo de SKUs y canales', horas: 6, fechaTentativa: '2026-08-06' },
      { fase: '3. Desarrollo Backend / APIs', accion: 'Configuración de triggers en ERP', horas: 12, fechaTentativa: '2026-08-14' },
      { fase: '6. Pruebas QA & Regresión', accion: 'Validación con equipo comercial', horas: 4, fechaTentativa: '2026-08-16' }
    ],
    d1: '2026-07-25', d2: '2026-07-28', d3: '2026-08-12', d4: '',
    d5: '', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-07-25', usuario: 'Camila Restrepo' },
      { de: 'Abertura', a: 'Analise', fecha: '2026-08-12', usuario: 'Lucía Fernández' }
    ],
    fechaCreacion: '2026-07-25', // > 20 días abierta -> Alerta SLA Excedido
    fechaCierre: '',
    ultimaModificacao: '2026-08-12T09:00:00Z',
    modificadoPor: 'Lucía Fernández'
  },
  {
    id: 'CHG-DEMO-003',
    spId: 1003,
    numeroChange: 'CHG0089290',
    ritm: 'RITM0145380',
    solicitante: 'Felipe Martins',
    pais: 'Brasil',
    businessService: 'Supply Chain Brasil',
    producto: 'KitKat',
    descripcion: 'Integración de calendario de temporadas especiales con el módulo de planificación de demanda',
    engenheiro: 'Diego Vargas',
    horasEstimadas: 28,
    horasAprovadas: 25,
    tipoChange: 'Mejora',
    faseAtual: 'Comite',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Juliana Costa',
    aprovadorEmail: 'juliana.costa@nestle.com',
    analise: 'Mapear festividades y correlacionar con histórico de ventas KitKat.',
    rollback: 'Revertir configuración del módulo de temporadas.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico & Requerimientos', accion: 'Definición de temporadas y curvas de demanda', horas: 8, fechaTentativa: '2026-08-08' },
      { fase: '5. Integración & Configuración', accion: 'Conectar API de calendario con motor de pronóstico', horas: 14, fechaTentativa: '2026-08-15' },
      { fase: '7. Pruebas UAT / Negocio', accion: 'Simulación con equipo de Demand Planning', horas: 6, fechaTentativa: '2026-08-18' }
    ],
    d1: '2026-08-05', d2: '2026-08-08', d3: '2026-08-10', d4: '2026-08-13',
    d5: '', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-05', usuario: 'Felipe Martins' },
      { de: 'Abertura', a: 'Comite', fecha: '2026-08-13', usuario: 'Diego Vargas' }
    ],
    fechaCreacion: '2026-08-05',
    fechaCierre: '',
    ultimaModificacao: '2026-08-13T14:00:00Z',
    modificadoPor: 'Diego Vargas'
  },
  {
    id: 'CHG-DEMO-004',
    spId: 1004,
    numeroChange: 'CHG0089315',
    ritm: 'RITM0145410',
    solicitante: 'Valeria Osorio',
    pais: 'Colombia',
    businessService: 'Data Lake Colombia',
    producto: 'Nido',
    descripcion: 'Reporte automatizado de sell-out semanal para distribuidores mayoristas de la región Andina',
    engenheiro: 'Carlos Mendoza',
    horasEstimadas: 15,
    horasAprovadas: 15,
    tipoChange: 'Mejora',
    faseAtual: 'Aprovacao',
    statusAprovacao: 'Aprovado',
    aprovadorNome: 'Esteban Morales',
    aprovadorEmail: 'esteban.morales@nestle.com',
    analise: 'Crear pipeline de ingesta automatizada desde SFTP mayoristas.',
    rollback: 'Volver a ingesta manual mediante archivo Excel semanal.',
    pasosImplementacion: [
      { fase: '3. Desarrollo Backend / APIs', accion: 'Configurar ETL de ingesta SFTP', horas: 8, fechaTentativa: '2026-08-11' },
      { fase: '6. Pruebas QA & Regresión', accion: 'Validación de cruces contra ventas sell-in', horas: 4, fechaTentativa: '2026-08-14' },
      { fase: '8. Despliegue & Producción', accion: 'Publicar tablero Power BI para distribuidores', horas: 3, fechaTentativa: '2026-08-16' }
    ],
    d1: '2026-08-07', d2: '2026-08-09', d3: '2026-08-11', d4: '2026-08-13',
    d5: '2026-08-15', d6: '2026-08-16', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-07', usuario: 'Valeria Osorio' },
      { de: 'Abertura', a: 'Aprovacao', fecha: '2026-08-16', usuario: 'Carlos Mendoza' }
    ],
    fechaCreacion: '2026-08-07',
    fechaCierre: '',
    ultimaModificacao: '2026-08-16T16:30:00Z',
    modificadoPor: 'Carlos Mendoza'
  },
  {
    id: 'CHG-DEMO-005',
    spId: 1005,
    numeroChange: 'CHG0089350',
    ritm: 'RITM0145490',
    solicitante: 'Gabriel Torres',
    pais: 'Argentina',
    businessService: 'Commercial Argentina',
    producto: 'La Lechera',
    descripcion: 'Ajuste de lista de precios dinámicos por canal de distribución tradicional',
    engenheiro: 'Lucía Fernández',
    horasEstimadas: 12,
    horasAprovadas: 12,
    tipoChange: 'Mejora',
    faseAtual: 'Concluida',
    statusAprovacao: 'Aprovado',
    aprovadorNome: 'Martín Palermo',
    aprovadorEmail: 'martin.palermo@nestle.com',
    analise: 'Actualizar matriz de descuentos por volumen en el portal B2B.',
    rollback: 'Cargar tabla de precios anterior desde backup.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico & Requerimientos', accion: 'Validación de listas con equipo Comercial', horas: 3, fechaTentativa: '2026-08-02' },
      { fase: '5. Integración & Configuración', accion: 'Carga masiva de tarifas en sistema comercial', horas: 6, fechaTentativa: '2026-08-04' },
      { fase: '7. Pruebas UAT / Negocio', accion: 'Pruebas de pedidos piloto', horas: 3, fechaTentativa: '2026-08-06' }
    ],
    d1: '2026-08-01', d2: '2026-08-02', d3: '2026-08-03', d4: '2026-08-04',
    d5: '2026-08-05', d6: '2026-08-05', d7: '2026-08-06', d8: '2026-08-07',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-01', usuario: 'Gabriel Torres' },
      { de: 'Abertura', a: 'Concluida', fecha: '2026-08-07', usuario: 'Lucía Fernández' }
    ],
    fechaCreacion: '2026-08-01',
    fechaCierre: '2026-08-07',
    ultimaModificacao: '2026-08-07T18:00:00Z',
    modificadoPor: 'Lucía Fernández'
  }
];
